### ISSUE TITLE
How metrics 'recall' and 'precision' are calculated?

### ISSUE THREAD

**Issue by Shanginre** [signals-dev/Orion#159]
The documentation describes how 'f1', 'accuracy' metrics are calculated. Everything is clear from them.

But I didn't find any mention of 'recall' and 'precision' metrics. I would like to know how they are calculated, how they differ from 'f1', 'accuracy' metrics  and how critical are they for evaluation a pipeline?

**Comment by sarahmish** [comment]
Hi @Shanginre, the recall and precision metrics follow the same standard as the remaining metrics, you can call them using `contextual_recall` and `contextual_precision`. 

To answer your question of how they are calculated, we first find the number of true positives, false positives, false negatives, and true negatives using either _weighted segment_ or _overlapping segment_. The exact procedure on how we do that is written [here](https://github.com/signals-dev/Orion/tree/master/orion/evaluation).

Now that we have our `tp, fp, fn, tn` the calculation is carried out as 
```python3
recall = tp / (tp + fn)
precision = tp / (tp + fp)
```

To answer the last question of how "critical" they are for evaluation really depends on what you are after. For example, if you want to detect all anomalies in your signal, then 'recall' is important because it gives you an indication of how many anomalies were missed. On the other hand, if you care about not raising too many false alarms, then 'precision' is important in this case. You can balance the two metrics by using 'f1 score' since it is the harmonic mean of both 'precision' and 'recall'.

I hope this answers your question!

**Comment by Shanginre** [comment]
@sarahmish thanks for the answer

**Comment by Shanginre** [comment]
I think it is worth including this in the documentation, since the meaning of these variables does not follow explicitly from their names
