### ISSUE TITLE
Is there pre-processing of data required?

### ISSUE THREAD

**Issue by juliabelford** [signals-dev/Orion#162]
* Orion version: 1.0.5
* Python version: 3.7.3
* Operating System: Windows 10

### Description

Describe what you were trying to get done.
Tell us what happened, what went wrong, and what you expected to happen.
Using the example but passing different data:

train_data.head()
timestamp   value
0   19941205  3490.1
1   19941212  3488.7
2   19941219  3485.8
3   19941226  3486.1
4   19950102  3480.3
### What I Did
orion.fit(train_data)
```
Paste the command(s) you ran and the output.
If there was a crash, please include the traceback here.
```
E0119 14:11:53.885504 28744 mlpipeline.py:552] Exception caught fitting MLBlock keras.Sequential.LSTMTimeSeriesRegressor#1
Traceback (most recent call last):
  File "c:\usr\Python37\lib\site-packages\mlblocks\mlpipeline.py", line 549, in _fit_block
    block.fit(**fit_args)
  File "c:\usr\Python37\lib\site-packages\mlblocks\mlblock.py", line 302, in fit
    getattr(self.instance, self.fit_method)(**fit_kwargs)
  File "c:\usr\Python37\lib\site-packages\mlprimitives\adapters\keras.py", line 98, in fit
    self._augment_hyperparameters(X, kwargs)
  File "c:\usr\Python37\lib\site-packages\mlprimitives\adapters\keras.py", line 89, in _augment_hyperparameters
    shape = np.asarray(X)[0].shape
IndexError: index 0 is out of bounds for axis 0 with size 0
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "c:\usr\Python37\lib\site-packages\orion\core.py", line 84, in fit
    self._mlpipeline.fit(data)
  File "c:\usr\Python37\lib\site-packages\mlblocks\mlpipeline.py", line 649, in fit
    self._fit_block(block, block_name, context)
  File "c:\usr\Python37\lib\site-packages\mlblocks\mlpipeline.py", line 549, in _fit_block
    block.fit(**fit_args)
  File "c:\usr\Python37\lib\site-packages\mlblocks\mlblock.py", line 302, in fit
    getattr(self.instance, self.fit_method)(**fit_kwargs)
  File "c:\usr\Python37\lib\site-packages\mlprimitives\adapters\keras.py", line 98, in fit
    self._augment_hyperparameters(X, kwargs)
  File "c:\usr\Python37\lib\site-packages\mlprimitives\adapters\keras.py", line 89, in _augment_hyperparameters
    shape = np.asarray(X)[0].shape
IndexError: index 0 is out of bounds for axis 0 with size 0

**Comment by sarahmish** [comment]
Hi @juliabelford!

The `train_data` you are showing does not require additional preprocessing if you are using one of our pipelines. Since you are using your own data, just make sure it follows the same format as we do, which is a `pd.DataFrame` with two columns (`timestamp`, `value`), similar to the one shown here
```
    timestamp     value
0  1222819200 -0.366359
1  1222840800 -0.394108
2  1222862400  0.403625
3  1222884000 -0.362759
4  1222905600 -0.370746
```

Additionally, you need to set the correct hyperparameters for your data!  Based on the frequency of your data you want to change `interval` to reflect that, in the default setting `interval=21600` which is equivalent to 6 hours. If your data is more frequent (5 minutes) then `interval=300` would be most appropriate. The units here are 1 second. 
**Note** that you can actually shrink your signal by aggregating it over too long of a period, which is what I presume happened in this case. 

Stitching it all together would show something like (I am assuming you are running `lstm_dynamic_threshold` pipeline):

```python3
hyperparameters = {
    "mlprimitives.custom.timeseries_preprocessing.time_segments_average#1": {
        "interval": 300
    },
    'keras.Sequential.LSTMTimeSeriesRegressor#1': {
        'epochs': 5,
        'verbose': True
    }
}

orion = Orion(
    pipeline='lstm_dynamic_threshold',
    hyperparameters=hyperparameters
)

orion.fit(train_data)
```
Changing the aggregating interval should fix your problem, but if it hasn't, would you mind giving a bit more detail on the length of the signal you are using and possibly sharing the entire code snippet so that I can try to reproduce it from my side?

**Comment by juliabelford** [comment]
My data are daily, so does the interval need to be 24*60*60?

**Comment by sarahmish** [comment]
Based on the input you are showing:
```
  timestamp   value
0  19941205  3490.1
1  19941212  3488.7
2  19941219  3485.8
3  19941226  3486.1
4  19950102  3480.3
```

The difference is:
* `timestamp[1] - timestamp[0] = 7` seconds
* `timestamp[2] - timestamp[1] = 7` seconds
* `timestamp[3] - timestamp[2] = 7` seconds
* `timestamp[4] - timestamp[3] = 8876` seconds

Since the majority of records seem to be 7 seconds apart, I would set `interval=7`.

**Comment by juliabelford** [comment]
setting the interval to 7 did not break the code. However, my timestamps are dates and not seconds. So how would I interpret this result? The test data are from 2020-01-01 till 2021-01-13
anomalies
      start       end  severity
0  20209748  20210112  2.870566

**Comment by sarahmish** [comment]
It depends on how did you convert your original timestamps, you should just invert it.

**Comment by kb1ooo** [comment]
@sarahmish Can you clarify how "interval" is used.  Suppose your time series has a consistent sample rate of 6 samples per minute, or every 10 seconds.    What does it mean to set the interval to something larger than 10, say 5 minutes like you originally suggested (`interval=300`)?

**Comment by sarahmish** [comment]
Hi @kb1ooo, sure! 

The purpose of the `mlprimitives.custom.timeseries_preprocessing.time_segments_average#1` primitive is to make your signal equi-spaced. If your signal's frequency is every 10 seconds, then the output of the primitive is a time series with a value at every 10 seconds.

Let's say you have the following signal
```
        timestamp    value
0      1404165600  10844.0
1      1404165900   8127.0
2      1404166200   6210.0
3      1404166800   3820.0
```
It's clear that the interval between each timestamp and the other is 300. Though notice there is a gap between instance 2 and 3, there should be a timestamp 1404166500. The primitive then creates a placeholder (`nan`) and assumes the imputation primitive will take care of it. The output would be `[[10844.], [ 8127.], [ 6210.], [   nan], [ 3820.]]`.

_What happens when you pick an interval larger than the frequency of your signal?_
In this case, it will take the average of values. Consider the same signal mentioned above and we set the interval to be 600, then we take the average of the interval. In this case the output would be `[[9485.5], [6210. ], [3820. ]]`.

Let me know if you need further clarification

**Comment by kb1ooo** [comment]
@sarahmish Thanks very much for your detailed reply.  One further question, what if you have multiple disjoint signals for training, that you don't want to interpolate over?   E.g. say you have several 5 day contiguous chunks of data.  

Thanks,  
Marc

**Comment by sarahmish** [comment]
Interesting case @kb1ooo

Our preprocessing primitives are based on the assumption that the signal is contiguous. _So what happens when the data is non-contiguous?_

**Running the pipeline without any changes**
As you would have guessed, the `mlprimitives.custom.timeseries_preprocessing.time_segments_average` primitive would introduce many `nan` into your signal, which will then get imputed but the resulting signal will not resemble your original signal and hence, the anomaly detection model might find anomalies because of the imputation artifact.

**Removing a primitive**
Assume that your signal is already equi-spaced within each chunk. Then technically you do not require the above primitive. However, the `mlprimitives.custom.timeseries_preprocessing.rolling_window_sequences` primitive will assume continuity and create training windows that interleave between days.

**Preprocess each chunk individually**
I would recommend applying the preprocessing steps on each disjoint segment individually. Piece the training examples together, and then train the model. Unfortunately, we don't support this right now.

**Run the pipeline on each chunk individually**
The last option would would to treat each chunk as a separate signal and run the pipeline on each one. In this case, you would be training several models which might not be ideal.

**Comment by kb1ooo** [comment]
@sarahmish Thanks again for the detailed reply.  I think your "Preprocess each chunk individually" makes the most sense, and is what I have done in the past for other implementations.  For realistic problems, I believe it's quite common to have training data with significant gaps that cannot be imputed.   You may even want to deliberately set it up that way for performance evaluation purposes (e.g. suppose you have 12 months of data, you may want to hold out 1 week of random data each month for testing, as opposed to say 10 months of contiguous data for training and 2 months for testing).     I'm not sure where the windowing/imputation happens, but it seems that  having a "maxgap" parameter which would specify the maximum gap in seconds over which you allow imputation, would make sense.  Your signal gets split on >maxgap gaps and fed to the windowing.   Can you point me to where I might look to see what those changes would entail?  

Thanks,  
Marc

**Comment by sarahmish** [comment]
@kb1ooo thanks for the suggestion. I opened a new issue relevant to the idea you are suggesting #171. 

I listed the primary primitives you would need to investigate there. The approach I am proposing does not alter the current implementation but rather is an additive. However, I believe you can investigate these primitives if you have a different approach; for imputation we directly use `sklearn.impute.SimpleImputer` and for windowing we use [mlprimitives.custom.timeseries_preprocessing.rolling_window_sequence](https://github.com/MLBazaar/MLPrimitives/blob/master/mlprimitives/custom/timeseries_preprocessing.py#L40).

**Comment by kb1ooo** [comment]
@sarahmish thank you, I will take a look per your suggestions in #171
