### ISSUE TITLE
24 seconds of data

### ISSUE THREAD

**Issue by CrowMagnumMan** [signals-dev/Orion#167]
* Orion version:  0.1.6.dev0
* Python version:  3.6.9
* Operating System:  Ubuntu 18.04.5 LTS

This is extremely interesting.  Your tutorial worked well.  I'd like to try this method on some data that consists of 24 second tranches of .01 sec resolution data points (2400 points).

In notebooks/tulog, both utils.py and tadgan.json seem to be hard-coded for New York Taxi data.  Is it correct to assume that these files are to be modified for custom (.csv) data?

Since Unix Time format is based in seconds, is there a recommended way to deal with data in .01 sec increments?

**Comment by sarahmish** [comment]
Hey @CrowMagnumMan 

Yes, the files accompanied with with tulog are expected to be modified. If you look within the `tadgan.json` you will note some specific parameters for the `nyc_taxi` data, for example `interval=1800` (you can read more about interval in #162).

The most granular level for configuration in Orion is seconds. However, technically the pipeline is oblivious to the unit of measurement. To use your data, I would project your data into seconds rather than .01 second increments and that would make your data span 24 minutes, and I would set `interval=1` which indicates that you have 1 second increments.

**Comment by CrowMagnumMan** [comment]
Huh.  That's exactly what I expected you to say.  That doesn't happen to me often.,  Thank you.  I'm going to try this.  It will take a few weeks to get the data together, then a couple after that, but I'll report back.  This is for a medical device application.

**Comment by sarahmish** [comment]
@CrowMagnumMan can you describe how the `timestamp` column is represented in your data? for example, is it similar to Unix Time format with an additional two digits? e.g. `[122284080000, 122284080001, ..]`?

**Comment by CrowMagnumMan** [comment]
The timestamp data is currently just basic numerical starting from time zero.  I can easily convert it to the Unix format, so that won't be an issue.

**Comment by sarahmish** [comment]
@CrowMagnumMan technically you do not need to convert it into Unix format as long as you have `1` increments. For example, if your data is close to the following representation, it should work fine

```
    timestamp     value
0           0 -0.366359
1           1 -0.394108
2           2  0.403625
3           3 -0.362759
4           4 -0.370746
```

In this case you have `1` increments and you need to setup the aggregation primitive as so
```python3
hyperparameters = {
    "mlprimitives.custom.timeseries_preprocessing.time_segments_average#1": {
        "interval": 1
    }
}
```

**Comment by sarahmish** [comment]
Closing this for now as the initial question was resolved, if you have a follow-up question, please feel free to re-open it!
