### ISSUE TITLE
[Question] Is LSTMTimeSeriesRegressor the same as TedGAN?

### ISSUE THREAD

**Issue by leix28** [signals-dev/Orion#185]
In readme, there's a method called TadGAN. It seems to be the best algorithm. But I'm not sure how to run Orion using this algorithm.

Can you show how to reproduce all three methods in the benchmark table?

**Comment by sarahmish** [comment]
Hi @leix28!

The title of your issue is a bit different, so I will answer both:
* The primitives referred to are different. LSTMTimeSeriesRegressor is a time series forecasting model using double stacked LSTM layers. On the other hand, TadGAN is a reconstruction based approach using a GAN model.
* To compare all three methods, you can use `orion.benchmark` for this task
```python3
from orion.benchmark import benchmark

# pipelines you want to compare
pipelines = [
    'arima',
    'lstm_dynamic_threshold',
    'tadgan'
]

# datasets you want to use for your benchmark
signals = ['S-1', 'P-1']

# metrics to report
metrics = ['f1', 'accuracy', 'recall', 'precision']

scores = benchmark(pipelines=pipelines, datasets=signals, metrics=metrics, rank='f1')
```

You can visit the [benchmark](https://github.com/signals-dev/Orion/blob/master/BENCHMARK.md) document for more detail.
