### ISSUE TITLE
Orion benchmark documentation clarifications

### ISSUE THREAD

**Issue by skyeeiskowitz** [signals-dev/Orion#187]
In the [Orion benchmark documentation](https://github.com/signals-dev/Orion/blob/master/BENCHMARK.md):

In the Arguments section:
1. The `distributed` argument is incomplete:

> distributed (bool): Whether to use dask for distributed computing. If not given,

2. The default of `test_split` is not specified:

> test_split (bool or float): Whether to use the prespecified train-test split. If float, then it should be between 0.0 and 1.0 and represent the proportion of the signal to include in the test split. If not given, use False

Underneath the Arguments section, is this referring to `_summarize_results` function (not `_summarize_results`) ?

> And returns a pandas.DataFrame which contains the scores obtained with each scoring function accross all the signals for each pipeline, optionally, you can follow that output with a summarize_results to average the scores and produce the leaderboard.

**Comment by sarahmish** [comment]
Thanks for the notes @skyeeiskowitz.

1. Definitely dropped some text here 
2. The default value is ``False`` but I will clarify the difference between ``bool`` and ``float`` inputs.
3. Actually I was meaning to extract ``_summarize_results`` out of `orion.benchmark` and include it in a separate `utils.py` file under `benchmark` where we keep the leaderboard results. Right now it does not make sense to be part of the `orion.benchmark` because it's a summary table used for a specific case. I will update this soon.
