### ISSUE TITLE
Ensure consistency between figures and text in tutorial notebook

### ISSUE THREAD

**Issue by zyteka** [signals-dev/Orion#188]
In the Google Colab Tulog notebook, right before the `End-to-End Pipeline Configuration` section, the text refers to the pipeline catching `4 out of 5 anomalies`. However, the image shown in the notebook that loaded in shows on 2 out of 5 being caught.

At the top of the notebook, the text does clarify that `the results might differ between runs`, but this disclaimer may be missed by someone skimming the results. Setting a random seed for the program to ensure the results look the same every time may prevent this confusion, or clarifying again that the image may not show 4 out of 5 anomalies if the run differs.

![image](https://user-images.githubusercontent.com/14080838/108002199-d4396c80-6fbc-11eb-8045-035a6676ec8a.png)

**Comment by sarahmish** [comment]
Thanks for pointing this out @zyteka! There is definitely some inconsistency here. I updated the colab notebook to mention `Several anomalies` rather than being specific. 

The stochasticity of `TadGAN` falls into two main parts: 
1. the random initialization of weights in the network
2. the sampling of the latent variable

Generally GANs are unstable because of their randomness and it would be difficult to ensure exactness.
