### ISSUE TITLE
Azure analysis example notebook unknown pipeline

### ISSUE THREAD

**Issue by skyeeiskowitz** [signals-dev/Orion#189]
From the Azure Analysis Example.ipynb last code block
> from orion.analysis import analyze
> 
> pipeline_path = '../orion/pipelines/azure.json'
> 
> anomalies = analyze(pipeline_path, data, hyperparams=hyperparameters)
> anomalies.head(5)

I get an unknown pipeline error: 
<img width="685" alt="Screen Shot 2021-02-15 at 11 01 46 PM" src="https://user-images.githubusercontent.com/38817247/108016982-c8ac6c80-6fe1-11eb-9361-087d80894dd6.png">

Should the pipeline path instead be:
> pipeline_path = '../orion/pipelines/verified/azure/azure.json'

**Comment by skyeeiskowitz** [comment]
May be solved by #176

**Comment by sarahmish** [comment]
Thanks @skyeeiskowitz, yes this error is resolved in PR #177.

Side note: to use azure you will need to pass a `subscription_key` and an `endpoint` parameters in either the hyperparameter settings or directly edit the pipeline, otherwise the pipeline will fail. 

If you have additional questions, please reopen the issue!
