### ISSUE TITLE
I was just wandering how we can load yahoo benchmark datasets using orion

### ISSUE THREAD

**Issue by salman087** [signals-dev/Orion#217]
* Orion version:
* Python version:
* Operating System:

### Description

Describe what you were trying to get done.
Tell us what happened, what went wrong, and what you expected to happen.

### What I Did

```
Paste the command(s) you ran and the output.
If there was a crash, please include the traceback here.
```

**Comment by sarahmish** [comment]
Hi @salman087, you need to request access to the [data from Yahoo](https://webscope.sandbox.yahoo.com/catalog.php?datatype=s&did=70) directly. It is not an open dataset and therefore we cannot host it.

**Note** that the raw dataset does not follow our [format](https://signals-dev.github.io/Orion/user_guides/data.html#data-format), more specifically, the dataset does not have a `timestamp` column. In order to use the yahoo data, you can generate a synthetic column `timestamp` for each entry point.

**Comment by salman087** [comment]
Thank you for your quick reply. I have another question if you could help me. As when we divide the e.g. NYC dataset into 60/40 split as training and test set. We don't know about the location and nature of known anomalies in advance in many cases. So there is the possibility that our model could be trained with anomalies. What could the possible solution for this?  Thanks

**Comment by sarahmish** [comment]
In our framework, we assume no prior knowledge of anomalies and hence do not take them into account when making train/test split. Training on signals with anomalies is a possibility, but since anomalies are scarce we assume that the model will not learn to predict/reconstruct them.

If you wish to remove anomalies prior to training, you might find some primitives helpful such as [masking](https://signals-dev.github.io/Orion/user_guides/primitives_pipelines/primitives/intervals_to_mask.html) to keep/remove parts of the signal, or you can manually divide your signal as well.
