### ISSUE TITLE
visualize known anomalies and detected anomalies

### ISSUE THREAD

**Issue by salman087** [signals-dev/Orion#229]
* Orion version:
* Python version:
* Operating System:

### Description

I need to visualize the anomalies detected by the model. I am using the plot(df,(anomalies,known_anomalies) to highlight the intervals. 
could you please give me any clue on how to customize and visualize correctly for any dataset. 

``

**Comment by sarahmish** [comment]
Hi @salman087,

the `plot` from `utils.py` is a simple approach to visualize the results, you can try to modify the [code](https://github.com/signals-dev/Orion/blob/master/notebooks/tulog/utils.py#L91) on your own to work well with your data, such as: changing the size of your plot, changing the title, etc. 

I advise you to create your own plotting function since that one in particular was created for the purpose of the tulog.
